### PR TITLE
Update _zaraxis.aiml

### PR DESCRIPTION
**Pull request by Miyuutsu**
Merged my previous request with _zaraxis.aiml and submitted. This must be present!

### CODE REVIEW

**Comment by JustArchi** [comment]
No closing </li>, syntax error.

**Comment by Zaraxis** [comment]
:+1:

**Comment by JustArchi** [comment]
Only syntax error to fix now. :+1: 

BTW, you can fix it by editing the file in your branch you want to merge. Let me know once it's ready.

**Comment by Miyuutsu** [comment]
Added closing li on the file in my branch. It apparently lost my change somehow, so I had to edit it all over again.

**Comment by JustArchi** [comment]
You updated master, while you want to merge patch-2.

> Miyuutsu  wants to merge 1 commit into JustArchi:master from Miyuutsu:patch-2

You should edit patch-2 branch then: https://github.com/Miyuutsu/ArchiBoT/commits/patch-2

**Comment by Miyuutsu** [comment]
Still new to GitHub. Fixed.

**Comment by JustArchi** [comment]
:+1:

**Pull request merged**
